Make click work
Without this commit, click will throw
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.